In [1]:
## This practice is designed for Indexing, Slicing and Iterating
import numpy as np

In [2]:
### Indexing, Slicing and Iterating
# Only one dimensional array can be indexed, sliced and iterated over.
# 只有一維陣列可以被 indexed, sliced, iterated over

# Sliced matrix.
# x[start index: stop before this index: interval]
# 矩陣切片
# x[起始索引:停止在此索引之前:間隔]
a = np.arange(10) ** 2
print("a=> {0}".format(a))
print()
print("a[2:5]=> {0}".format(a[2:5]))
print()

# sliced
# 從index為3起算,每數到4的元素值都改為9999,直到第8個元素(index為7)為止
a[3:8:4] = 9999
print("a[3:8:4]=> {0}".format(a))

print()
a = np.arange(10) ** 2
# reversed
# 倒序
print("a[:,:,-1])=> {0}".format(a[::-1]))
print()

# Iteracted over
for i in a:
    print("a**(1/2)=> {0}".format(np.round(i**(1/2), 0)))

a=> [ 0  1  4  9 16 25 36 49 64 81]

a[2:5]=> [ 4  9 16]

a[3:8:4]=> [   0    1    4 9999   16   25   36 9999   64   81]

a[:,:,-1])=> [81 64 49 36 25 16  9  4  1  0]

a**(1/2)=> 0.0
a**(1/2)=> 1.0
a**(1/2)=> 2.0
a**(1/2)=> 3.0
a**(1/2)=> 4.0
a**(1/2)=> 5.0
a**(1/2)=> 6.0
a**(1/2)=> 7.0
a**(1/2)=> 8.0
a**(1/2)=> 9.0


In [3]:
## Form function
def my_f(row, col):
    return row*5 + col

b = np.fromfunction(my_f, (5, 5), dtype=int)
print(b)

print()
print(b[0:5, 4])

print()
print(b[:, 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 4  9 14 19 24]

[ 4  9 14 19 24]


In [4]:
# 多維陣列在for loop中取值時，會以第一維度為優先！
# 以二維陣列為例：一層for loop優先獲取的陣列內容，就是第一維度每row的內容
b = np.arange(1, 41).reshape(5, 8)

print()
# for loop
for row in b:
    print(row)


[1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16]
[17 18 19 20 21 22 23 24]
[25 26 27 28 29 30 31 32]
[33 34 35 36 37 38 39 40]


In [5]:
# 直接將矩陣內所有元素扁平化，依序取出所有元素！此功能必須搭配for-loop, while-loop使用
# flat
b = np.arange(1, 13).reshape(3, 4)
for element in b.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
