In [1]:
import numpy as np

In [5]:
##Simple Assignments
##簡易指定

# 簡易指定並非真正複製內容
a = np.arange(12)
# This will assign the a's address to b instead of copy the content of a to b.
# 這會把a的記憶體位址指定給b, 並非真正複製內容
b = a
print("b等於a嗎？:{0}".format(b is a))
print("a的形狀:{0}".format(a.shape))
print("b的形狀:{0}".format(b.shape))

# changes the shape of a
# 改變a陣列的形狀
print("\n改變a的形狀")
a.shape = 3, 4
print("a的形狀:{0}".format(a.shape))
print("b的形狀:{0}".format(b.shape))

print()
print("The array of features of simple assignments:")
print("簡單指定陣列的特性:")
print("\tb is a:? {0}".format(b is a))
print("\tb is base on who:? {0}".format(b.base))
print("\tb.flags.owndata:? {0}".format(b.flags.owndata))

b等於a嗎？:True
a的形狀:(12,)
b的形狀:(12,)

改變a的形狀
a的形狀:(3, 4)
b的形狀:(3, 4)

The array of features of simple assignments:
簡單指定陣列的特性:
	b is a:? True
	b is base on who:? None
	b.flags.owndata:? True


In [6]:
# View or Shallow Copy
# 檢視/淺拷貝

# View
# 檢視
a = np.arange(12)
c = a.view()
print("a=>\n{0}".format(a))
print("c=>\n{0}".format(c))

print()
# Changes the shape of c.
# 改變c陣列的形狀
c.shape = 3, 4
print("c.shape=3,4\nc=>\n{0}".format(c))
print("a=>\n{0}".format(a))

print()
# Let's change some element value of c.
# 來變更c的元素值看看
c[1,2] = 999
print("c[1,2]=999\nc=>\n{0}".format(c))
print("a=>\n{0}".format(a))

print()
# Slices an array will return a view of it.
# If you change elements' value of the view, the related elements' value of source array will be changed simultaneously.
# 對陣列/矩陣切片,會回傳檢視喔!
# 如果你更改了檢視的元素值,來源陣列的相對應的元素值也會同時被改變!
s = c[:, 1:3]
print("s=c[:, 1:3]\ns=>\n{0}".format(s))
s[:] = 10
print("s[:] = 10\ns=>\n{0}".format(s))
print("c=>\n{0}".format(c))

print()
print("The Features of View:")
print("View的特性:")
print("\tc is a:? {0}".format(c is a))
print("\tc is base on who:? {0}".format(c.base))
print("\tc.flags.owndata:? {0}".format(c.flags.owndata))

a=>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
c=>
[ 0  1  2  3  4  5  6  7  8  9 10 11]

c.shape=3,4
c=>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a=>
[ 0  1  2  3  4  5  6  7  8  9 10 11]

c[1,2]=999
c=>
[[  0   1   2   3]
 [  4   5 999   7]
 [  8   9  10  11]]
a=>
[  0   1   2   3   4   5 999   7   8   9  10  11]

s=c[:, 1:3]
s=>
[[  1   2]
 [  5 999]
 [  9  10]]
s[:] = 10
s=>
[[10 10]
 [10 10]
 [10 10]]
c=>
[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]

The Features of View:
View的特性:
	c is a:? False
	c is base on who:? [ 0 10 10  3  4 10 10  7  8 10 10 11]
	c.flags.owndata:? False


In [4]:
##Deep Copy
##深度拷貝
a = np.arange(12)
b = a.copy()
print("a=>{0}".format(a))
print("b=>{0}".format(b))

print()
print("The Features of Deep Copy:")
print("Deep Copy的特性:")
print("b is a:? {0}".format(b is a))
print("b is base on who:? {0}".format(b.base))
print("b.flags.owndata:? {0}".format(b.flags.owndata))

print()
b[5] = 99
print("b[5] = 999\nb=> {0}".format(b))
print("a=> {0}".format(a))

print()
b.shape = 2, 6
print("b.shape = 2,6\nb=>\n{0}".format(b))
print("a=> {0}".format(a))

a=>[ 0  1  2  3  4  5  6  7  8  9 10 11]
b=>[ 0  1  2  3  4  5  6  7  8  9 10 11]

The Features of Deep Copy:
Deep Copy的特性:
b is a:? False
b is base on who:? None
b.flags.owndata:? True

b[5] = 999
b=> [ 0  1  2  3  4 99  6  7  8  9 10 11]
a=> [ 0  1  2  3  4  5  6  7  8  9 10 11]

b.shape = 2,6
b=>
[[ 0  1  2  3  4 99]
 [ 6  7  8  9 10 11]]
a=> [ 0  1  2  3  4  5  6  7  8  9 10 11]
