In [1]:
import numpy as np

In [2]:
##Shape Manipulation
# 矩陣的形狀
# the shape of matrix/array.
a = np.arange(1, 51).reshape(5, 10)
print("a =>\n",format(a))
print("a.shape:",format(a.shape))

a =>
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
a.shape: (5, 10)


In [3]:
a = np.arange(1, 51).reshape(5, 10)
# reshape(): 改變陣列的維度
# reshape(): change the shape of array.
print("a.reshape(5, 2, 5)=>\n{0}".format(a.reshape(5, 2, 5)))

print()
# reshape()可以使用-1的選項讓NumPy自動幫你計算維度大小
# -1 is a option of reshape, that can automatically calcuate the other dimensions.
print("a.reshape(5, 2, -1)=>\n{0}".format(a.reshape(5, 2, -1)))

a.reshape(5, 2, 5)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]

a.reshape(5, 2, -1)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]


In [4]:
# ravel(): 回傳一個陣列，這個陣列是經過扁平化處理的陣列
# ravel(): returns an array that is flattened.
a = np.arange(1, 51).reshape(5, 10)
print("a.ravel()=> {0}".format(a.ravel()))

a.ravel()=> [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [5]:
# T: 將陣列或矩陣轉置
# T: Transpose an array or matrix.
b = np.arange(1, 7).reshape(2, 3)
print("b =>\n{0}".format(b))

print()
print("轉置矩陣b(Transpose b.)\n=>\n{0}".format(b.T))

b =>
[[1 2 3]
 [4 5 6]]

轉置矩陣b(Transpose b.)
=>
[[1 4]
 [2 5]
 [3 6]]


In [6]:
##Stacking together different arrays
# 將不同的矩陣堆疊在一起
a = np.arange(1,11).reshape(2,5)
print("a=>\n{0}".format(a))

print()
# Stacking 2 arrays along a horizontal axis.
# 將2個陣列沿著水平軸堆疊起來
print("np.hstack((a,a))=>\n{0}".format(np.hstack((a,a))))

print()
# Stacking 2 arrays along a vertical axis.
# 將2個陣列沿著垂直軸堆疊起來
print("np.vstack((a,a))=>\n{0}".format(np.vstack((a,a))))

a=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

np.hstack((a,a))=>
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]

np.vstack((a,a))=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
##Splitting one array into several smaller ones
a = np.round(np.arange(1, 13).reshape(2, 6)*10, 0)
print("a=>\n{0}".format(a))

print()
print("----hsplit----")
# hsplit(array, N): 沿著水平軸切成三個矩陣
# hsplit(array, N): Split an array into N arries/matrices along its horizontal axis.
output1 = np.hsplit(a, 3)
i = 0
for smallMatrix in output1:
    print("np.hsplit(a, 3) [{0}]=>\n{1}".format(i, smallMatrix))
    i+=1

print("Type of output1: {0}".format(type(output1)))
newOutput1 = np.array(output1)
print("Shape of output1: {0}".format(newOutput1.shape))

print()
print("----vsplit----")
# vsplit(array, N): 沿著垂直軸切成三個矩陣
# vsplit(array, N): Split an array into N arries/matrices along its vertical axis.
output2 = np.vsplit(a, 2)
i = 0
for smallMatrix in output2:
    print("np.vsplit(a, 2) [{0}]=>{1}".format(i, smallMatrix))
    i+=1
print()
print("Type of output2: {0}".format(type(output2)))
newOutput2 = np.array(output2)
print("Shape of output2: {0}".format(newOutput2.shape))

a=>
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]

----hsplit----
np.hsplit(a, 3) [0]=>
[[10 20]
 [70 80]]
np.hsplit(a, 3) [1]=>
[[ 30  40]
 [ 90 100]]
np.hsplit(a, 3) [2]=>
[[ 50  60]
 [110 120]]
Type of output1: <class 'list'>
Shape of output1: (3, 2, 2)

----vsplit----
np.vsplit(a, 2) [0]=>[[10 20 30 40 50 60]]
np.vsplit(a, 2) [1]=>[[ 70  80  90 100 110 120]]

Type of output2: <class 'list'>
Shape of output2: (2, 1, 6)
