In [1]:
import numpy as np

In [2]:
##ix_()

martix_a = np.arange(0, 25).reshape(5, 5)
print('matrix_a=>\n', martix_a)

# ix_() will return a tuple what is composed by array [1,3] and array [2,4].
# ix_() 會回傳一個由[1,3]和[2,4]兩個輸入值而組成的tuple.
print()
print('np.ix_([1,3],[2,4]))')
print('ix_()=>\n{0}'.format(np.ix_([1,3],[2,4])))

# We can seperate the return value of ix_() as two different array.
# 我們可以分別將ix_()的回傳值以兩個不同的陣列取出.
print()
print('Seperate the return value of ix_(): rows, cols = np.ix_([1,3],[2,4])')
rows, cols = np.ix_([1,3],[2,4])
print('rows=>\n{0}\ncols=>\n{1}'.format(rows, cols))

# The return value of ix_() can divide into two part:
# The first part will is composed by the first input array,
# and the first part will become a column vector.
# The second part is composed by the second input array,
# and it will become a row vector.
# Therefor, we can use the return value of ix_() as an index set
# to get values from a 2-dimension matrix directly.
# ix_()的回傳值分為兩個部分：
# 第一部分由第一個輸入陣列組成, 它會變成一個column vector. 
# 第二部分由第二個輸入陣列組成, 它會變成一個row vector. 
# 因此, 我們可以利用ix_()的回傳值形成一組索引集, 直接從一個二維陣列中取值.
print()
print('Get values by ix_():')
print('a_ix = martix_a[ np.ix_([1,3],[2,4]) ]')
a_ix = martix_a[np.ix_([1,3],[2,4])]
print('a_ix=>\n{0}'.format(a_ix))

matrix_a=>
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

np.ix_([1,3],[2,4]))
ix_()=>
(array([[1],
       [3]]), array([[2, 4]]))

Seperate the return value of ix_(): rows, cols = np.ix_([1,3],[2,4])
rows=>
[[1]
 [3]]
cols=>
[[2 4]]

Get values by ix_():
a_ix = martix_a[ np.ix_([1,3],[2,4]) ]
a_ix=>
[[ 7  9]
 [17 19]]


In [3]:
##Linear Algebra
x1 = np.array([[1, 2], [3, 4]], dtype=np.float32).reshape(2,2)
x2 = np.array([5, 6], dtype=np.float32).reshape(2,1)
print('x1=>\n{0}\nx2=>\n{1}'.format(x1, x2))

# matrix product
# 矩陣相乘
print()
print('x1 product x2=>\n{0}'.format(np.dot(x1, x2)))

# element-by-element multiplication
# 矩陣內元素相乘
print()
print('x1 times x2=>\n{0}'.format(x1*x2))

# transpose
# 轉置矩陣
print()
print('transpose x1=>\n{0}'.format(np.transpose(x1)))

# identity matrix
# 單位矩陣
print()
print('identify matrix I=>\n{0}'.format(np.eye(3)))



x1=>
[[1. 2.]
 [3. 4.]]
x2=>
[[5.]
 [6.]]

x1 product x2=>
[[17.]
 [39.]]

x1 times x2=>
[[ 5. 10.]
 [18. 24.]]

transpose x1=>
[[1. 3.]
 [2. 4.]]

identify matrix I=>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
##Repeat / Tile / hstack / vstack
col = np.arange(0,3).reshape(3,1)
print('col=>\n{0}'.format(col))

# Repeat col for 5 times along the 2nd axis.
# 沿著第2軸，重製col 5次
a = np.repeat(col, 5, axis=1)
print()
print('repeat col for 5 times=>\n{0}'.format(a))

# Repeat col 2 times along the direction of 1st dimension,
# and repeat col 4 times along the direction of 2nd dimension.
# 沿著第一個維度的方向重複col 2次, 沿著第二個維度的方向重複col 4次.
a = np.tile(col, (2,4))
print()
print('repeat col like [2,4]=>\n{0}'.format(a))

# Stack col with horizontal line.
# 將col沿著水平線堆疊.
print()
print('hstack col=>\n{0}'.format(np.hstack([col, col])))

# Stack col with vertical line.
# 將col沿著垂直線堆疊.
print()
print('vstack col=>\n{0}'.format(np.vstack([col, col])))

col=>
[[0]
 [1]
 [2]]

repeat col for 5 times=>
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]

repeat col like [2,4]=>
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

hstack col=>
[[0 0]
 [1 1]
 [2 2]]

vstack col=>
[[0]
 [1]
 [2]
 [0]
 [1]
 [2]]
