In [2]:
import numpy as np

In [5]:
##Indexing with Arrays of Indices
a = np.arange(10)**2
print('a=>{0}'.format(a))
i = np.array([1, 3, 5, 7, 9])
print('i=> {0}'.format(i))
print('a[i]=> {1}'.format(i, a[i]))

print("")
a = np.arange(10)**2
j = np.array( [[3, 4], [5, 6]] )
print('a=>{0}'.format(a))
print('j=>\n{0}'.format(j))
# Transforms the shape of a into j, and gets values.
# 把a的形狀改成像j的形狀, 而且取得相對應index的值.
print('a[j]=>\n{0}'.format(a[j]))

print()
print("Gets values by 2 arrays from a matrix.")
x = np.arange(28).reshape(4, 7)
a = np.array([[0, 1], [2, 3]])
b = np.array([[5, 5], [6, 6]])
print("x=>\n{0}".format(x))
print("a=>\n{0}".format(a))
print("b=>\n{0}".format(b))
# Array "a" will indicate the indices of row of the matrix "x".
# Array "b" will indicate the indices of column of the matrix "x".
# 陣列a將會指出矩陣x裡的row
# 陣列b將會指出矩陣x裡的column
print("x[a,b]=>\n{0}".format(x[a,b]))

a=>[ 0  1  4  9 16 25 36 49 64 81]
i=> [1 3 5 7 9]
a[i]=> [ 1  9 25 49 81]

a=>[ 0  1  4  9 16 25 36 49 64 81]
j=>
[[3 4]
 [5 6]]
a[j]=>
[[ 9 16]
 [25 36]]

Gets values by 2 arrays from a matrix.
x=>
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
a=>
[[0 1]
 [2 3]]
b=>
[[5 5]
 [6 6]]
x[a,b]=>
[[ 5 12]
 [20 27]]


In [13]:
x = np.array([[1, 2, 3], [6, 5, 5], [7, 8, 9]])
print("x=>\n{0}".format(x))
print()
# Find out the indices of max value along axis-0.
# In this case, axis-0 means each rows in a 2 dimensional matrix.
# 同column位置之中 數值最大位置的的row索引值.
print("x.argmax(axis=0)=>{0}".format(x.argmax(axis=0)))
# Find out the indices of max value along axis-1.
# In this case, axis-1 means each columns in a 2 dimensional matrix.
# 同row位置之中 數值最大位置的的column的索引.
print("np.argmax(x, axis=1)=>{0}".format(np.argmax(x, axis=1)))


print()
# Find out the max values from each colunm of a 2 dimensional matrix.
# 印出2維度陣列中, 各row對應至每一column的最大的值
print("x=>\n{0}".format(x))
print("Max in each colunms:")
for idx in range(x.shape[1]):
    print( "The MAX value of column-{0}=> {1}".format(idx, x[x.argmax(axis=0)[idx], idx]) )

print()
# Summarize the values by each corresponding columns of a 2 dimensional matrix.
# 加總每一個相對應欄位的數值
print("x=>\n{0}".format(x))
print("np.sum(x, axis=0)=>{0}".format(np.sum(x, axis=0)))

x=>
[[1 2 3]
 [6 5 5]
 [7 8 9]]

x.argmax(axis=0)=>[2 2 2]
np.argmax(x, axis=1)=>[2 0 2]

x=>
[[1 2 3]
 [6 5 5]
 [7 8 9]]
Max in each colunms:
The MAX value of column-0=> 7
The MAX value of column-1=> 8
The MAX value of column-2=> 9

x=>
[[1 2 3]
 [6 5 5]
 [7 8 9]]
np.sum(x, axis=0)=>[14 15 17]
