In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5, 5)
# 從矩陣a中篩選出數值小於20的index位置，並依此邏輯建立篩選器filter
filter = a < 20

print('a=>\n{0}'.format(a))
# 看看篩選器filter長怎樣
print('filter=>\n{0}'.format(filter))
print('')
print('Replace numbers with zero that number is small than 20:')
# 直接將篩選器作為index數值，將篩選器數值為True對應到a矩陣位置的數值更改為0
a[filter] = 0
print('a=>\n{0}'.format(a))

a=>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
filter=>
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]

Replace numbers with zero that number is small than 20:
a=>
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [20 21 22 23 24]]


In [3]:
a = np.arange(12).reshape(3,4)
print('a=>\n{0}'.format(a))

print('')
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])
print('b1=>{0}'.format(b1))
print('b2=>{0}'.format(b2))

print('')
print('Display rows in matrix "a" that are selected by array "b1":')
# 使用b1作為矩陣a的row篩選器，印出b1值為True對應到a矩陣的數值
print('a[b1,:]=>\n{0}'.format(a[b1,:]))

print('')
print('Display columns in matrix "a" that are selected by array "b2":')
# 使用b2作為矩陣a的column篩選器，印出b2值為True對應到a矩陣的數值
print('a[:,b2]=>\n{0}'.format(a[:,b2]))

a=>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b1=>[False  True  True]
b2=>[ True False  True False]

Display rows in matrix "a" that are selected by array "b1":
a[b1,:]=>
[[ 4  5  6  7]
 [ 8  9 10 11]]

Display columns in matrix "a" that are selected by array "b2":
a[:,b2]=>
[[ 0  2]
 [ 4  6]
 [ 8 10]]
