In [15]:
# This practice is designed for "Basic Operations".
import numpy as np

In [16]:
print('維度相同的矩陣相加、減:')
# 維度相同的矩陣相加、減
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))


print('\n同加、同減一個數值:')
# 同加、同減一個數值
a += 5
print("a=>{0}".format(a))
b -= 5
print("b=>{0}".format(b))


print('\n次方：')
# d是b的2次方
# d is squared of b.
d = b**2
print("d=>{0}".format(d))

維度相同的矩陣相加、減:
a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]

同加、同減一個數值:
a=>[11 12 13 14]
b=>[-5 -4 -3 -2]

次方：
d=>[25 16  9  4]


In [17]:
a = np.arange(5)
b = np.arange(10, 5, -1)
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("\n同除:")
# c等於a同除以2
c = a / 2
print("c=>{0}".format(c))

print("\n同乘:")
# d等於b同乘以2
d = b * 2
print("d=>{0}".format(b))

a=>[0 1 2 3 4]
b=>[10  9  8  7  6]

同除:
c=>[0.  0.5 1.  1.5 2. ]

同乘:
d=>[10  9  8  7  6]


In [18]:
# 矩陣相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A, B相乘(矩陣乘法) =>\n{0}".format(A.dot(B)))
print()
print("A, B相對應位置相乘=>\n{0}".format(A*B))

A, B相乘(矩陣乘法) =>
[[19 22]
 [43 50]]

A, B相對應位置相乘=>
[[ 5 12]
 [21 32]]


In [19]:
# 印出陣列中小於等於0的元素
e = np.array([5, -1, 3, 9, 0])
print("陣列e裡面哪幾個位置的元素值小於等於零?:{0}".format(e<=0))

# 把小於等於0的元素取代成1
e[e<=0] = 1
print("把小於等於0的元素取代成1=>{0}".format(e))

陣列e裡面哪幾個位置的元素值小於等於零?:[False  True False False  True]
把小於等於0的元素取代成1=>[5 1 3 9 1]


In [20]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.float)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a

print("b=>\n{0}".format(b))


a += b
print("a=>\n{0}".format(a))

a=>
[[5. 5. 5.]
 [5. 5. 5.]]
b=>
[[5.72531846 5.56334825 5.01618382]
 [5.19603197 5.57285526 5.70528792]]
a=>
[[10.72531846 10.56334825 10.01618382]
 [10.19603197 10.57285526 10.70528792]]


In [21]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.int)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a
# float64 = float64 + int64
print("b=>\n{0}".format(b))

# int64 = int64 + float64
# This will get errors! Because, the precision of int is shorter than float.
# 這邊應該會出錯, 因為int64的長度比float64還要短.
# a += b
# print("a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[5.03566471 5.51034935 5.64901554]
 [5.39860411 5.97754978 5.51620688]]


In [22]:
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))

sum=>5.122329871308706
max=>0.9983574553837268
min=>0.009791451172560972
mean=>0.5691477634787451


In [23]:
b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))

print()
# 加總每一欄(column)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))

print()
# 加總每一列(row)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=1)))

print()
revenu = np.round(np.random.random((1,12)) * 100, 0)
print("revenu=>\n{0}".format(revenu))

print()
# 累計加總(每一項數值等於自己加上前一項)
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

b.sum(axis=0)=>[ 6  8 10 12 14 16]

b.sum(axis=0)=>[15 51]

revenu=>
[[29. 26. 68. 50. 58. 31. 80.  8. 45. 36. 35. 41.]]

Cumulative Sum of revenu=>
[ 29.  55. 123. 173. 231. 262. 342. 350. 395. 431. 466. 507.]


In [26]:
B = np.arange(3)
# Exponential function
# 自然函數運算
B_exp = np.exp(B)
print("B_exp=> {0}".format(B_exp))

# Square root of B
# B的平方根
B_sqrt = np.sqrt(B)
print("B_sqrt=> {0}".format(B_sqrt))

# Array "A" pluses array "B".
# 陣列A加上陣列B.
C = np.array([2, 1, 0])
print("np.add(B, C)=> {0}".format(np.add(B, C)))

B_exp=> [1.         2.71828183 7.3890561 ]
B_sqrt=> [0.         1.         1.41421356]
np.add(B, C)=> [2 2 2]
