In [1]:
## This lesson is designed for "Basics" & "Array Creation"

In [2]:
import numpy as np

In [3]:
## Data type of array
a = np.array([1, 2, 3, 4, 5])
print("a=>{0}".format(a))
print("b.dtype=>{0}".format(a.dtype))
print()
b = np.array([1.25, 2.25, 3.25, 4.25, 5.25])
print("b.dtype=>{0}".format(b.dtype))

a=>[1 2 3 4 5]
b.dtype=>int32

b.dtype=>float64


In [4]:
## 1 dimension array.
## 1維陣列
a = np.array([6, 5, 4, 3, 2])
print("a=>{0}".format(a))
print()
b = np.arange(10)
print("b=>{0}".format(b))
print()
c = np.arange(0, 10, 1.5, dtype=np.float64)
print("c=>{0}".format(c))

a=>[6 5 4 3 2]

b=>[0 1 2 3 4 5 6 7 8 9]

c=>[0.  1.5 3.  4.5 6.  7.5 9. ]


In [5]:
## 2 dimension array. (2-by-3 matrix)
## 2維陣列 2-by-3 array
b = np.array([[1.1, 1.2, 1.3], [2.1, 2.2, 2.3]])
print("b=>{0}".format(b))

b=>[[1.1 1.2 1.3]
 [2.1 2.2 2.3]]


In [6]:
## Declare c1 as a complex array/matrix.
## 宣告c1為一個複數矩陣
c1 = np.array([(1.1, 1.2, 1.3), (2.1, 2.2, 2.3)], dtype=complex)
print("c1=>{0}".format(c1))
print()
c2 = np.array([2.1+6j, 3.2+9j, 4.3+12j])
print("c2=>{0}".format(c2))

c1=>[[1.1+0.j 1.2+0.j 1.3+0.j]
 [2.1+0.j 2.2+0.j 2.3+0.j]]

c2=>[2.1 +6.j 3.2 +9.j 4.3+12.j]


In [7]:
## Assign a particular data type to an array.
## 指定一個特定的資料型態給陣列.
aa = np.array([(1.9, 1.5, 1.3), (2.9, 2.5, 2.3)], dtype=np.int16)
print("aa=>{0}".format(aa))

aa=>[[1 1 1]
 [2 2 2]]


In [8]:
# What's the different between array in Python and array in NumPy?
# Array in NumPy is based on a class called "ndarray", and this class support multi-dimension matrix operations.
# Array in Python is developed from the standard libraries in Python. it only supports one-dimension operations, and the functions or options are less than NumPy.
# NumPy中的array和Python的array有何不同呢？
# NumPy的array是NumPy中名為ndarray的Class所定義的，而這個array當然支援多維度陣列，也可以說它是一個支援Martix的類別！
# Python的array則是標準函式庫內建的Class-->array.array。他只能支援單維度的陣列，而且提供的功能選項也比NumPy來得少！

# ndarray.ndim: the numbers of dimension of ndarray object
# ndarray.ndim: ndarray物件的維度
print("ndim:{0}".format(aa.ndim))

# ndarry.shape: the size of each dimension of ndarry objects. it returns a Tuple.
# ndarry.shape: ndarry物件的每一個維度的大小(size)，回傳資料類別為Tuple
print("shape:{0}".format(aa.shape))

# ndarry.size: it summarizes the number of elements in this ndarray object. the returns value will equal to the each elements of ndarray.shape times to each other.
# ndarry.size: ndarry物件所組成之array的總元素數量，回應之數值會等於ndarray.shape的每個元素相乘
print("size:{0}".format(aa.size))

# ndarry.dtype: the data type of ndarray object.
# ndarry.dtype: ndarray物件內組成元素的型態
print("dtype:{0}".format(aa.dtype))

# ndarray.itemsize: the data size of elements in array.(Bytes)
# ndarray.itemsize: 陣列中每一個元素的大小(Bytes) (ex: int16=>16/8=2 Bytes)
print("itemsize:{0}".format(aa.itemsize))

# ndarry.data: This is an address of an array. It usually keeps some buffer in memory.
# ndarry.data: 這是一個存有實際陣列元素的緩衝，通常我們不需要使用這個屬性，因為我們可以使用index存取這些元素。
print("data:{0}".format(aa.data))

ndim:2
shape:(2, 3)
size:6
dtype:int16
itemsize:2
data:<memory at 0x000001FA8412CDC8>


In [9]:
## Zeros
zeros = np.zeros( (3, 5) )
print("zeros=>{0}".format(zeros))

zeros=>[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
## Ones
ones = np.ones( (3, 5) )
print("ones=>{0}".format(ones))

ones=>[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
## Empty
## It means that we want to declare a uninitialized matrix.
e = np.empty( (2, 5) )
print("e=>{0}".format(e))

e=>[[1.07480582e-311 1.07480582e-311 0.00000000e+000 0.00000000e+000
  4.94065646e-324]
 [0.00000000e+000 0.00000000e+000 2.12199579e-314 0.00000000e+000
  4.94065646e-324]]


In [12]:
## Arange
r1 = np.arange(25, 30, .5)
print("r1=>{0}".format(r1))

r1=>[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [13]:
## Linspace
lin = np.linspace(3, 5, 9)
print("lin=>\n{0}".format(lin))

lin=>
[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
